services:
  api_gateway:
    build: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      - PORT=${API_GATEWAY_PORT}
      - SHORTENER_SERVICE_URL=http://shortener_service:${SHORTENER_SERVICE_PORT}
      - REDIRECT_SERVICE_URL=http://redirect_service:${REDIRECT_SERVICE_PORT}
    depends_on:
      - shortener_service
      - redirect_service
    networks:
      - url_shortener_net

  shortener_service:
    build: ./shortener-service
    ports:
      - "${SHORTENER_SERVICE_PORT}:${SHORTENER_SERVICE_PORT}"
    environment:
      - PORT=${SHORTENER_SERVICE_PORT}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - url_shortener_net

  redirect_service:
    build: ./redirect-service
    ports:
      - "${REDIRECT_SERVICE_PORT}:${REDIRECT_SERVICE_PORT}"
    environment:
      - PORT=${REDIRECT_SERVICE_PORT}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:${REDIS_PORT}
    depends_on:
      - db
      - redis
    networks:
      - url_shortener_net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - url_shortener_net

  redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - url_shortener_net

volumes:
  db_data:

networks:
  url_shortener_net:
    driver: bridge
